namespace: crossplane-system

helmCharts:
- name: crossplane
  repo: https://charts.crossplane.io/stable
  version: 1.12.0
  releaseName: crossplane
  namespace: crossplane-system
  includeCRDs: true
