controller:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 150Mi
    limits:
      cpu: 100m
      memory: 150Mi
  config:
    use-forwarded-headers: "true"
    force-ssl-redirect: "true"
