namespace: cert-manager

resources:
  - google-public-ca.yaml

# https://github.com/cert-manager/cert-manager/tree/master/deploy/charts/cert-manager
helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: 1.12.0
  releaseName: cert-manager
  namespace: cert-manager
  includeCRDs: true
  valuesFile: ./values.yaml
