namespace: kube-system

helmCharts:
- name: metrics-server
  repo: https://kubernetes-sigs.github.io/metrics-server/
  version: 3.10.0
  releaseName: metrics-server
  namespace: kube-system
  includeCRDs: true
  valuesFile: ./insecure-tls/values.yaml
