apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-headers
  namespace: argocd
spec:
  project: local
  destination:
    namespace: default
  source:
    chart: microservice
    repoURL: https://dolldot.github.io/manifests
    targetRevision: 0.1.3
    helm:
      releaseName: echo-headers
      valuesObject:
        replicaCount: 1

        image:
          repository: brndnmtthws/nginx-echo-headers
          tag: latest
          pullPolicy: IfNotPresent

        service:
          port: 8080

        ingress:
          enabled: false
