namespace: external-secrets

resources:
- cluster-secret-store.yaml

helmCharts:
- name: external-secrets
  repo: https://charts.external-secrets.io
  version: 0.8.3
  releaseName: external-secrets
  namespace: external-secrets
  includeCRDs: true
