apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-additional-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: argocd-additional-secret
  data:
  - secretKey: oidc.github.clientID
    remoteRef:
      key: argocd-secrets
      property: clientID
  - secretKey: oidc.github.clientSecret
    remoteRef:
      key: argocd-secrets
      property: clientSecret
  - secretKey: oidc.github.orgName
    remoteRef:
      key: argocd-secrets
      property: orgName
