namespace: argocd

resources:
- additional-secret.yaml
- repo-creds.yaml

# https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 5.51.6
  releaseName: argocd
  namespace: argocd
  includeCRDs: true
  valuesFile: ./values.yaml
