apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dot-git-creds
  namespace: argocd
spec:
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: dot-git-creds
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: git@github.com:dolldot
        sshPrivateKey: '{{ .privKey }}'
  data:
  - secretKey: privKey
    remoteRef:
      key: ssh-priv
      property: priv_key
