apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zerossl-eab-secret
spec:
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: zerossl-eab-secret
  data:
    - secretKey: eab-hmac-key
      remoteRef:
        key: zerossl-eab
        property: hmac-key
