apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: crossplane-aws-creds
      key: creds
