apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crossplane-aws-creds
spec:
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: crossplane-aws-creds
    template:
      data:
        creds: |
          [default]
          aws_access_key_id = {{ .id }}
          aws_secret_access_key = {{ .secret }}

  data:
  - secretKey: id
    remoteRef:
      key: crossplane-creds
      property: AccessKey.AccessKeyId
  - secretKey: secret
    remoteRef:
      key: crossplane-creds
      property: AccessKey.SecretAccessKey
