namespace: cert-manager

resources:
  - cloudflare

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: 1.12.0
  releaseName: cert-manager
  namespace: cert-manager
  includeCRDs: true
  valuesFile: ./base/values.yaml
