fullnameOverride: internal-clydev-com-nginx

controller:
  electionID: internal-clydev-com-nginx
  ingressClass: internal-clydev-com-nginx
  ingressClassResource:
    name: internal-clydev-com-nginx
  service:
    targetPorts:
      http: http
      https: https
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 150Mi
    limits:
      cpu: 100m
      memory: 150Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - internal-clydev-com-nginx
  config:
    use-forwarded-headers: "true"
    force-ssl-redirect: "true"
