apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onic-echo-headers
  namespace: argocd
spec:
  destination:
    name: k3s-lab
    namespace: default
  project: default
  source:
    chart: microservice
    helm:
      releaseName: echo-headers
      values: |
        replicaCount: 1

        image:
          repository: brndnmtthws/nginx-echo-headers
          tag: latest
          pullPolicy: IfNotPresent

        service:
          port: 8080
    repoURL: https://dolldot.github.io/manifests
    targetRevision: 0.1.3
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onic-todo
  namespace: argocd
spec:
  destination:
    name: k3s-lab
    namespace: default
  project: default
  source:
    chart: microservice
    helm:
      releaseName: todo
      values: |
        replicaCount: 1

        image:
          repository: prologic/todo
          tag: latest
          pullPolicy: IfNotPresent

        service:
          port: 8000
    repoURL: https://dolldot.github.io/manifests
    targetRevision: 0.1.3
