apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    rollme: {{ randAlphaNum 16 | quote }}
spec:
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name }}
    kind: {{ .Values.secretStoreRef.kind }}
  target:
    name: {{ include "microservice.fullname" . }}
  data:
  {{- range $k, $v := .Values.secrets }}
  {{- range $key, $val := $v }}
  - secretKey: {{ $key }}
    remoteRef:
      key: {{ $k }}
      property: {{ $val }}
  {{- end }}
  {{- end }}
