apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-public-ca-eab-secret
spec:
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: google-public-ca-eab-secret
  data:
  - secretKey: eab_hmac_key
    remoteRef:
      key: publicca-google
      property: b64MacKey
